/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import javax.swing.JCheckBox;

/**
 *
 * @author Sarita
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    public boolean fiestaArdillas(int numBellotas, boolean finDeSemana) {
        if (finDeSemana) {
            return true;
        }
        if (numBellotas >= 40 && numBellotas <= 60) {
            return true;
        }
        return false;
    }

    public int multa(int velocidad, boolean cumple) {
        if (cumple) {
            velocidad = velocidad - 5;
        }
        if (velocidad <= 60) {
            return 0;
        }
        if ((velocidad >= 61) && (velocidad <= 81)) {
            return 1;
        }
        return 2;
    }

    public boolean vanidoso(int numero) {
        if ((numero % 11 == 0) || (numero % 11 == 1)) {
            return true;
        }
        return false;
    }

    public boolean contesta(boolean matinal, boolean madre, boolean dormido) {
        if (dormido) {
            return false;
        }
        if (madre && matinal) {
            return true;
        }
        if (matinal) {
            return false;
        }
        return true;
    }

    public boolean menorPor10(int numero1, int numero2, int numero3) {
        if ((Math.abs(numero1 - numero2) >= 10) || (Math.abs(numero1 - numero3) >= 10) || (Math.abs(numero2 - numero3) >= 10)) {
            return true;
        }
        return false;
    }

    public boolean digitoIgual(int a, int b) {
        int aIzq = a / 10;
        int aDer = a % 10;
        int bIzq = b / 10;
        int bDer = b % 10;
        if (aIzq == bDer || aIzq == bIzq || aDer == bIzq || aDer == bDer) {
            return true;
        }
        return false;
    }

    public boolean multiploMultiple(int a) {
        if (a % 3 == 0 && a % 5 == 0) {
            return false;
        }
        if (a % 3 == 0 || a % 5 == 0) {
            return true;
        }
        return false;
    }

    public boolean menos20(int a) {
        if ((((a + 1) % 20) == 0) || (((a + 2) % 20) == 0)) {
            return true;
        }
        return false;
    }

    public int loteria(int a, int b, int c) {
        if (a == b && a != c) {
            return 0;
        }
        if (a == 2 && b == 2 && c == 2) {
            return 10;
        } else {
            return 5;
        }
    }

    public int withoutDoubles(int a, int b, boolean noDoubles) {
        int resultado = a + b;
        if ((noDoubles == true) && (a == b)) {
            resultado++;
        }
        return resultado;
    }

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Solucion = new javax.swing.JLabel();
        ACTIVIDADES = new javax.swing.JTabbedPane();
        Multa = new javax.swing.JPanel();
        Velocidad = new javax.swing.JLabel();
        VelocidadConductor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TickCumpleaños = new javax.swing.JCheckBox();
        Policia = new javax.swing.JButton();
        Vanidoso = new javax.swing.JPanel();
        Numero = new javax.swing.JLabel();
        NumeroVanidoso = new javax.swing.JTextField();
        EsVanidoso = new javax.swing.JButton();
        Contesta = new javax.swing.JPanel();
        Mama = new javax.swing.JLabel();
        SiMama = new javax.swing.JCheckBox();
        Dormido = new javax.swing.JLabel();
        SiDormido = new javax.swing.JCheckBox();
        Mañana = new javax.swing.JLabel();
        SiMañana = new javax.swing.JCheckBox();
        Responde = new javax.swing.JButton();
        DigitoIgual = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Coincide = new javax.swing.JButton();
        Dado1 = new javax.swing.JTextField();
        Dado2 = new javax.swing.JTextField();
        Multiplo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NumeroQueTeDan = new javax.swing.JTextField();
        Menos20 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        numerito = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        Loteria = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NumeroA = new javax.swing.JTextField();
        NumeroB = new javax.swing.JTextField();
        NumeroC = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        WithoutDoubles = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Dadito1 = new javax.swing.JTextField();
        Dadito2 = new javax.swing.JTextField();
        SinDoble = new javax.swing.JButton();
        SinDobles = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        Ardillas = new javax.swing.JPanel();
        TextoNumeroDeBellotas = new javax.swing.JLabel();
        NumeroDeBellotas = new javax.swing.JTextField();
        TickFinDeSemana = new javax.swing.JCheckBox();
        TextoFinDeSemana = new javax.swing.JLabel();
        Fiesta = new javax.swing.JButton();
        MenorPor10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Numero1 = new javax.swing.JTextField();
        Numero2 = new javax.swing.JTextField();
        Numero3 = new javax.swing.JTextField();
        SonDiezMenos = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Solucion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Solucion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Velocidad.setText("Velocidad del conductor:");

        jLabel4.setText("Cumpleaños:");

        TickCumpleaños.setText("Es mi cumpleaños");

        Policia.setText("¡POLICIA!");
        Policia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MultaLayout = new javax.swing.GroupLayout(Multa);
        Multa.setLayout(MultaLayout);
        MultaLayout.setHorizontalGroup(
            MultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultaLayout.createSequentialGroup()
                .addGroup(MultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MultaLayout.createSequentialGroup()
                                .addComponent(Velocidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VelocidadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MultaLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TickCumpleaños, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MultaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Policia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        MultaLayout.setVerticalGroup(
            MultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VelocidadConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TickCumpleaños))
                .addGap(18, 18, 18)
                .addComponent(Policia, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("Multa", Multa);

        Numero.setText("Numero:");

        EsVanidoso.setText("¿SERÁ VANIDOSO?");
        EsVanidoso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsVanidosoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VanidosoLayout = new javax.swing.GroupLayout(Vanidoso);
        Vanidoso.setLayout(VanidosoLayout);
        VanidosoLayout.setHorizontalGroup(
            VanidosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VanidosoLayout.createSequentialGroup()
                .addGroup(VanidosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VanidosoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(EsVanidoso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VanidosoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NumeroVanidoso, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(509, Short.MAX_VALUE))
        );
        VanidosoLayout.setVerticalGroup(
            VanidosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VanidosoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(VanidosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero)
                    .addComponent(NumeroVanidoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(EsVanidoso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("Vanidoso", Vanidoso);

        Mama.setText("¿Será mi madre?");

        SiMama.setText("Sí, es mama");

        Dormido.setText("¿Estoy dormido?");

        SiDormido.setText("Sí, estoy dormido");

        Mañana.setText("¿Es por la mañana?");

        SiMañana.setText("Sí, es por la mañana");

        Responde.setText("¿RESPONDE LA LLAMADA?");
        Responde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespondeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContestaLayout = new javax.swing.GroupLayout(Contesta);
        Contesta.setLayout(ContestaLayout);
        ContestaLayout.setHorizontalGroup(
            ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContestaLayout.createSequentialGroup()
                .addGroup(ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContestaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContestaLayout.createSequentialGroup()
                                .addComponent(Dormido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SiDormido))
                            .addGroup(ContestaLayout.createSequentialGroup()
                                .addComponent(Mama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SiMama))
                            .addGroup(ContestaLayout.createSequentialGroup()
                                .addComponent(Mañana, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SiMañana))))
                    .addGroup(ContestaLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Responde, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        ContestaLayout.setVerticalGroup(
            ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContestaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiMama))
                .addGap(18, 18, 18)
                .addGroup(ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dormido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiDormido))
                .addGap(18, 18, 18)
                .addGroup(ContestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mañana, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SiMañana))
                .addGap(18, 18, 18)
                .addComponent(Responde, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        ACTIVIDADES.addTab("Contesta", Contesta);

        jLabel6.setText("Dado1:");

        jLabel7.setText("Dado2:");

        Coincide.setText("¿COINCIDE?");
        Coincide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoincideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DigitoIgualLayout = new javax.swing.GroupLayout(DigitoIgual);
        DigitoIgual.setLayout(DigitoIgualLayout);
        DigitoIgualLayout.setHorizontalGroup(
            DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DigitoIgualLayout.createSequentialGroup()
                .addGroup(DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DigitoIgualLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Dado1)
                            .addComponent(Dado2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .addGroup(DigitoIgualLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Coincide, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        DigitoIgualLayout.setVerticalGroup(
            DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DigitoIgualLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DigitoIgualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DigitoIgualLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Dado2)))
                .addGap(18, 18, 18)
                .addComponent(Coincide, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("DigitoIgual", DigitoIgual);

        jLabel8.setText("Numero que te dan:");

        jButton1.setText("¿ES MÚLTIPLO?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MultiploLayout = new javax.swing.GroupLayout(Multiplo);
        Multiplo.setLayout(MultiploLayout);
        MultiploLayout.setHorizontalGroup(
            MultiploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiploLayout.createSequentialGroup()
                .addGroup(MultiploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MultiploLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumeroQueTeDan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MultiploLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(529, Short.MAX_VALUE))
        );
        MultiploLayout.setVerticalGroup(
            MultiploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiploLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MultiploLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroQueTeDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("MultiploMultiple", Multiplo);

        jLabel9.setText("Numero:");

        jButton2.setText("¿MENOS DE 20?");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menos20Layout = new javax.swing.GroupLayout(Menos20);
        Menos20.setLayout(Menos20Layout);
        Menos20Layout.setHorizontalGroup(
            Menos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menos20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Menos20Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numerito, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        Menos20Layout.setVerticalGroup(
            Menos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menos20Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Menos20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numerito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("Menos20", Menos20);

        jLabel10.setText("NumeroA:");

        jLabel11.setText("NumeroB:");

        jLabel12.setText("NumeroC:");

        jButton3.setText("RESULTADO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoteriaLayout = new javax.swing.GroupLayout(Loteria);
        Loteria.setLayout(LoteriaLayout);
        LoteriaLayout.setHorizontalGroup(
            LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoteriaLayout.createSequentialGroup()
                .addGroup(LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoteriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LoteriaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(NumeroA, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoteriaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(NumeroB))
                            .addGroup(LoteriaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(NumeroC))))
                    .addGroup(LoteriaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        LoteriaLayout.setVerticalGroup(
            LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoteriaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NumeroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(NumeroB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(NumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("Loteria", Loteria);

        jLabel13.setText("Dado1:");

        jLabel14.setText("Dado2:");

        SinDoble.setText("¿SON DOBLES?");
        SinDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinDobleActionPerformed(evt);
            }
        });

        SinDobles.setText("No dobles");

        jLabel15.setText("¿Son dobles?");

        javax.swing.GroupLayout WithoutDoublesLayout = new javax.swing.GroupLayout(WithoutDoubles);
        WithoutDoubles.setLayout(WithoutDoublesLayout);
        WithoutDoublesLayout.setHorizontalGroup(
            WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithoutDoublesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(WithoutDoublesLayout.createSequentialGroup()
                            .addComponent(SinDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(WithoutDoublesLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Dadito1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(WithoutDoublesLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(Dadito2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(WithoutDoublesLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SinDobles)))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        WithoutDoublesLayout.setVerticalGroup(
            WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WithoutDoublesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dadito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Dadito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(WithoutDoublesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SinDobles)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(SinDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("WithoutDoubles", WithoutDoubles);

        TextoNumeroDeBellotas.setText("Numero de bellotas:");

        TickFinDeSemana.setText("Fin de Semana");

        TextoFinDeSemana.setText("Fin de Semana:");

        Fiesta.setText("¡FIESTA!");
        Fiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ArdillasLayout = new javax.swing.GroupLayout(Ardillas);
        Ardillas.setLayout(ArdillasLayout);
        ArdillasLayout.setHorizontalGroup(
            ArdillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArdillasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArdillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArdillasLayout.createSequentialGroup()
                        .addComponent(TextoNumeroDeBellotas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TextoFinDeSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ArdillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumeroDeBellotas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TickFinDeSemana))
                .addGap(504, 504, 504))
            .addGroup(ArdillasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Fiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ArdillasLayout.setVerticalGroup(
            ArdillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArdillasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ArdillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoNumeroDeBellotas)
                    .addComponent(NumeroDeBellotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ArdillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TickFinDeSemana)
                    .addComponent(TextoFinDeSemana))
                .addGap(18, 18, 18)
                .addComponent(Fiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("Ardillas", Ardillas);

        jLabel2.setText("Numero 1:");

        jLabel3.setText("Numero 2:");

        jLabel5.setText("Numero 3:");

        SonDiezMenos.setText("¿SON DIEZ MENOS?");
        SonDiezMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SonDiezMenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenorPor10Layout = new javax.swing.GroupLayout(MenorPor10);
        MenorPor10.setLayout(MenorPor10Layout);
        MenorPor10Layout.setHorizontalGroup(
            MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenorPor10Layout.createSequentialGroup()
                .addGroup(MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenorPor10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenorPor10Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Numero3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenorPor10Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenorPor10Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Numero2))))
                    .addGroup(MenorPor10Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(SonDiezMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(506, Short.MAX_VALUE))
        );
        MenorPor10Layout.setVerticalGroup(
            MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenorPor10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenorPor10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SonDiezMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        ACTIVIDADES.addTab("MenorPor10", MenorPor10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Solucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ACTIVIDADES)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ACTIVIDADES, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(Solucion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiestaActionPerformed
        //leo el contenido de la caja de texto y lo convierto a integer
        //supongo que el usuario solo va a esribir numeros
        int numeroBellotas = Integer.parseInt(NumeroDeBellotas.getText());
        if (fiestaArdillas(numeroBellotas, TickFinDeSemana.isSelected())) {
            Solucion.setText("LA FIESTA ES UN EXITO");
        } else {
            Solucion.setText("LA FIESTA ES UNA F EN EL CHAT");
        }
    }//GEN-LAST:event_FiestaActionPerformed

    private void PoliciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliciaActionPerformed
      int multaDelPolicia = Integer.parseInt(VelocidadConductor.getText());
      int resultado = multa(multaDelPolicia, TickCumpleaños.isSelected());
      if(resultado == 0){
          Solucion.setText("NO HAY MULTA");
      }
      else if (resultado ==1){
          Solucion.setText("MULTA PEQUEÑA");
      }
      else{
          Solucion.setText("MULTA GRANDE");
      }
    }//GEN-LAST:event_PoliciaActionPerformed

    private void EsVanidosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsVanidosoActionPerformed
       int resultadoVanidoso = Integer.parseInt(NumeroVanidoso.getText());
       if (vanidoso (resultadoVanidoso)){
           Solucion.setText("MUY VANIDOSO");
       }
       else{
           Solucion.setText("NO ES VANIDOSO");
       }
    }//GEN-LAST:event_EsVanidosoActionPerformed

    private void RespondeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespondeActionPerformed
     if (contesta(SiMañana.isSelected(), SiMama.isSelected(), SiDormido.isSelected())) {
         Solucion.setText("RESPONDE");
     }
     else{
         Solucion.setText("NO RESPONDE");
     }
    }//GEN-LAST:event_RespondeActionPerformed

    private void SonDiezMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SonDiezMenosActionPerformed
       int numero1 = Integer.parseInt(Numero1.getText());
       int numero2 = Integer.parseInt(Numero2.getText());
       int numero3 = Integer.parseInt(Numero3.getText());
        if (menorPor10(numero1, numero2, numero3)) {
         Solucion.setText("SI ES MENOR POR 10");
     }
     else{
         Solucion.setText("NO ES MENOR POR 10");
     }
          
    }//GEN-LAST:event_SonDiezMenosActionPerformed

    private void CoincideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoincideActionPerformed
       int dado1 = Integer.parseInt(Dado1.getText());
       int dado2 = Integer.parseInt(Dado2.getText());
       if (digitoIgual(dado1, dado2)) {
         Solucion.setText("EL DIGITO ES IGUAL");
     }
     else{
         Solucion.setText("EL DIGITO NO ES IGUAL");
     }
    }//GEN-LAST:event_CoincideActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int numeroquemedan = Integer.parseInt(NumeroQueTeDan.getText());
        if (multiploMultiple(numeroquemedan)) {
         Solucion.setText("ES MULTIPLO");
     }
     else{
         Solucion.setText("NO ES MULTIPLO");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int numero = Integer.parseInt(numerito.getText());
        if (menos20(numero)) {
         Solucion.setText("ES MENOS DE 20");
     }
     else{
         Solucion.setText("NO ES MENOS DE 20");
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int loteriaA = Integer.parseInt(NumeroA.getText());
       int loteriaB = Integer.parseInt(NumeroB.getText());
       int loteriaC = Integer.parseInt(NumeroC.getText());
       int resultado = loteria(loteriaA, loteriaB, loteriaC);
      if(resultado == 0){
          Solucion.setText("NO TE TOCA LA LOTERIA");
      }
      else if (resultado == 5){
          Solucion.setText("TE TOCA UNA PEQUEÑA PARTE");
      }
      else{
          Solucion.setText("TE TOCO LA LOTERIA");
      }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SinDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinDobleActionPerformed
      int dadito1 = Integer.parseInt(Dadito1.getText());
      int dadito2 = Integer.parseInt(Dadito2.getText());
      int resultado = withoutDoubles (dadito1, dadito2,SinDobles.isSelected());  
      Solucion.setText("EL RESULTADO ES: " + resultado );
     
    }//GEN-LAST:event_SinDobleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ACTIVIDADES;
    private javax.swing.JPanel Ardillas;
    private javax.swing.JButton Coincide;
    private javax.swing.JPanel Contesta;
    private javax.swing.JTextField Dadito1;
    private javax.swing.JTextField Dadito2;
    private javax.swing.JTextField Dado1;
    private javax.swing.JTextField Dado2;
    private javax.swing.JPanel DigitoIgual;
    private javax.swing.JLabel Dormido;
    private javax.swing.JButton EsVanidoso;
    private javax.swing.JButton Fiesta;
    private javax.swing.JPanel Loteria;
    private javax.swing.JLabel Mama;
    private javax.swing.JLabel Mañana;
    private javax.swing.JPanel MenorPor10;
    private javax.swing.JPanel Menos20;
    private javax.swing.JPanel Multa;
    private javax.swing.JPanel Multiplo;
    private javax.swing.JLabel Numero;
    private javax.swing.JTextField Numero1;
    private javax.swing.JTextField Numero2;
    private javax.swing.JTextField Numero3;
    private javax.swing.JTextField NumeroA;
    private javax.swing.JTextField NumeroB;
    private javax.swing.JTextField NumeroC;
    private javax.swing.JTextField NumeroDeBellotas;
    private javax.swing.JTextField NumeroQueTeDan;
    private javax.swing.JTextField NumeroVanidoso;
    private javax.swing.JButton Policia;
    private javax.swing.JButton Responde;
    private javax.swing.JCheckBox SiDormido;
    private javax.swing.JCheckBox SiMama;
    private javax.swing.JCheckBox SiMañana;
    private javax.swing.JButton SinDoble;
    private javax.swing.JCheckBox SinDobles;
    private javax.swing.JLabel Solucion;
    private javax.swing.JButton SonDiezMenos;
    private javax.swing.JLabel TextoFinDeSemana;
    private javax.swing.JLabel TextoNumeroDeBellotas;
    private javax.swing.JCheckBox TickCumpleaños;
    private javax.swing.JCheckBox TickFinDeSemana;
    private javax.swing.JPanel Vanidoso;
    private javax.swing.JLabel Velocidad;
    private javax.swing.JTextField VelocidadConductor;
    private javax.swing.JPanel WithoutDoubles;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numerito;
    // End of variables declaration//GEN-END:variables
}
